version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: .dockerfile
    image: github.com/hyperyuri/webapi-db
    container_name: webapi-mvc-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - ./book.sql:/docker-entrypoint-initdb.d/book.sql
  api:
    build:
      context: .
      dockerfile: ./server/dockerfile
    ports:
      - "4000:5000"
    depends_on:
      - db

volumes:
  webapi-mvc: