version: "3.7"

services:
  db:
    build: db/.
    image: github.com/hyperyuri/webapi-db
    container_name: webapi-mvc-db
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - ./db/book.sql:/docker-entrypoint-initdb.d/book.sql
  api:
    build:
      context: .
      dockerfile: .dockerfile
    image: golang:latest
    ports:
      - "4000:5000"
    depends_on:
      - db
    volumes:
      - .:/go/src/webapi-with-go

volumes:
  webapi-mvc: